### ISSUE TITLE
The backdrop-filter feature takes too much GPU usage on my computer

### ISSUE THREAD

**Issue by XinRoom** [yang991178/fluent-reader#307]
**Describe the bug**

I found that I turned on the Gaussian Blur on my GPU (i5-10210U core display), which took up too high and stuttered.

**To Reproduce**
1. View switch to compact view
2. Click on the list item
3. Sliding

**Expected behavior**
There is a switch to enable Gaussian blur in the settings.

**Screenshots**
GPU is around 70% when backdrop-filter is enabled:

![image](https://user-images.githubusercontent.com/32238570/130267309-5eb65f40-e72e-4faa-bc97-d2f2b9bba2db.png)

The corresponding code is:
```css
.article-container {
    backdrop-filter: var(--blur);
    animation-name: fade;
    background-color: #0008;
}
```

After closing, it will be about 24%.

**Platform (please complete the following information):**
 - OS: [Windows 10 20H2]
 - Version [1.0.2]
